{
 "title": "Microservices monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Global status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Micros running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 1 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(jvm_memory_used_bytes{job=\"user-micro\", area=\"nonheap\", id!=\"Metaspace\"})",
     "legendFormat": "user-micro"
    },
    {
     "expr": "max(jvm_memory_used_bytes{job=\"order-micro\", area=\"nonheap\", id!=\"Metaspace\"})",
     "legendFormat": "order-micro"
    }
   ]
  },
  { "title": "Users Micro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "up{job=\"user-micro\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"user-micro\", area=\"nonheap\", id!=\"Metaspace\"}",
     "legendFormat": "{{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "Requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus\", job=\"user-micro\"}[5m])",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  { "title": "Orders micro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Service up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "up{job=\"order-micro\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"order-micro\", area=\"nonheap\", id!=\"Metaspace\"}",
     "legendFormat": "{{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "Requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus\", job=\"order-micro\"}[5m])",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  }
 ]
}