server:
  port: 8080  # Gateway port

spring:
  application:
    name: gateway  # Gateway service name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery with Eureka
          lower-case-service-id: true  # Ensures service names are matched in lowercase
      routes:
        - id: order-micro
          uri: lb://ORDER-MICRO  # Load-balance to instances of order-micro
          predicates:
            - Path=/**
        - id: user-micro
          uri: lb://USER-MICRO  # Load-balance to instances of user-micro
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO